# Generated by Django 2.2 on 2020-03-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_posted_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.Message')),
                ('user_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.User')),
            ],
        ),
    ]
